### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by Phulieu** [AHupuJR/RFNet#7]
I am training with only cityscapes dataset 
But I have some error below:
IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "C:\Users\parke\.conda\envs\untitled\lib\site-packages\torch\utils\data\_utils\worker.py", line 198, in _worker_loop
    data = fetcher.fetch(index)
  File "C:\Users\parke\.conda\envs\untitled\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\parke\.conda\envs\untitled\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "E:\RFNet-master\dataloaders\datasets\cityscapes.py", line 54, in __getitem__
    lbl_path = self.labels[self.split][index].rstrip()
IndexError: list index out of range

**Comment by AHupuJR** [comment]
That promblem seems not exist here in my local repository. Maybe you can debug and check your path

**Comment by tahaboub** [comment]
I am also having the same issue, I am wondering if it was resolved, Below is a similar issue or error, which I can't tell how it is originated. Any hint or recommendation that will highly appreciate it.

PS C:\dev1\RFNet> python train.py --depth --lr 1e-4 --weight-decay 2.5e-5 --workers 4 --epochs 200 --batch-size 8 --val-batch-size 3 --gpu-ids 0 --checkname test --eval-interval 2 --dataset cityscapes --loss-type ce --use-balanced-weights
Namespace(base_size=1024, batch_size=8, checkname='test', crop_size=768, cuda=False, dataset='cityscapes', depth=True, epochs=200, eval_interval=2, ft=False, gpu_ids='0', loss_type='ce', lr=0.0001, lr_scheduler='cos', momentum=0.9, no_cuda=False, no_val=False, resume=None, seed=1, start_epoch=0, test_batch_size=1, use_balanced_weights=True, val_batch_size=3, weight_decay=2.5e-05, workers=4)
Found 2975 train RGB images
Found 2975 train disparity images
Found 500 val RGB images
Found 500 val disparity images
Found 1525 test RGB images
Found 1525 test disparity images
Upsample layer: in = 128, skip = 64, out = 128
Upsample layer: in = 128, skip = 128, out = 128
Upsample layer: in = 128, skip = 256, out = 128
pretrained dict loaded sucessfully
  0%|                                                                                          | 0/372 [00:00<?, ?it/s]Calculating classes weights
  0%|                                                                                          | 0/372 [00:04<?, ?it/s]
Traceback (most recent call last):
  File "train.py", line 308, in <module>
    main()
  File "train.py", line 297, in main
    trainer = Trainer(args)
  File "train.py", line 51, in __init__
    weight = calculate_weigths_labels(args.dataset, self.train_loader, self.nclass)
  File "C:\dev1\RFNet\utils\calculate_weights.py", line 12, in calculate_weigths_labels
    for sample in tqdm_batch:
  File "C:\Users\Admin\anaconda3\envs\th16\lib\site-packages\tqdm\std.py", line 1185, in __iter__
    for obj in iterable:
  File "C:\Users\Admin\anaconda3\envs\th16\lib\site-packages\torch\utils\data\dataloader.py", line 521, in __next__
    data = self._next_data()
  File "C:\Users\Admin\anaconda3\envs\th16\lib\site-packages\torch\utils\data\dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "C:\Users\Admin\anaconda3\envs\th16\lib\site-packages\torch\utils\data\dataloader.py", line 1229, in _process_data
    data.reraise()
  File "C:\Users\Admin\anaconda3\envs\th16\lib\site-packages\torch\_utils.py", line 425, in reraise
    raise self.exc_type(msg)
IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "C:\Users\Admin\anaconda3\envs\th16\lib\site-packages\torch\utils\data\_utils\worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "C:\Users\Admin\anaconda3\envs\th16\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\Admin\anaconda3\envs\th16\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\dev1\RFNet\dataloaders\datasets\cityscapes.py", line 53, in __getitem__
    lbl_path = self.labels[self.split][index].rstrip()
IndexError: list index out of range

**Comment by TobiasMei** [comment]
I think it is a similar problem that I had when running eval.py.

In the dataloder file in this line:
https://github.com/AHupuJR/RFNet/blob/e1358018c5d75c5d3361a668ca4516e6d72946f9/dataloaders/datasets/cityscapes.py#L32
There is the suffix: 'labelTrainIds.png' set, but in my case the downloaded cityscapes dataset is named without 'Train' in the name. So i replaced the suffix with 'labelIds.png' and everything worked for me.

I hope this will also solve your problem.

**Comment by finetune-master** [comment]
##### This error reminds you to generate labelTrainIds.png.You can refer to this blog https://blog.csdn.net/lx_ros/article/details/125667076.
